### ISSUE TITLE
Impossible de lancer la bête?

### ISSUE THREAD

**Issue by Rakambda** [om3g4zell/PianoProject#2]
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at main.Main.main(Main.java:21)
Caused by: java.lang.NullPointerException
	at org.jsfml.internal.SFMLNative.readMD5File(Unknown Source)
	at org.jsfml.internal.SFMLNative.loadNativeLibraries(Unknown Source)
	at org.jsfml.window.VideoMode.<clinit>(Unknown Source)
	... 1 more
```

**Comment by om3g4zell** [comment]
Bizarre chez moi ça marche

**Comment by Qu3tzal** [comment]
La JSFML n'est plus supportée depuis quelques années déjà.
Y'a peut être un soucis avec les libs SFML natives sur Mac.

**Comment by Rakambda** [comment]
Ok ok, j'avais bien les .dylib et ai essayé avec [ça](https://github.com/pdinklag/JSFML/wiki/Windows#windows-on-mac-os-x) mais ça marche pas non plus.
On va dire que la lib est outdated  👍

EDIT: D'après ce que j'ai vu, JSFML supporte SFML 2.2? Et vu que j'ai la 2.4... Si y'aurait des libs à jour ce serai cool 😂 Y'a bien quelqu'un qui a fort JSFML et l'a update non?
